name: chest
version: 0.1.2
description: A flexible in-memory database with amazing developer experience.
repository: https://github.com/chestdb/chest

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  more: ^3.0.1

dev_dependencies:
  test: any
  glados: any
