name: chest
version: 0.0.4-0
repository: https://github.com/marcelgarus/chest
description: A flexible in-memory database with amazing developer experience.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  more: ^3.0.0-nullsafety.4

dev_dependencies:
  test: any
  glados: any
