name: chest
version: 0.0.1-0
repository: https://github.com/marcelgarus/chest
description: An in-memory database with amazing developer experience.

dependencies:
  more: ^3.0.0-nullsafety.4

environment:
  sdk: '>=2.12.0-0 <3.0.0'
